version: '3'
services:
  jenkins:
    image: "vixns/jenkins-dind"
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_data:/var/lib/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
